### ISSUE TITLE
Question / colors

### ISSUE THREAD

**Issue by rstudner** [ruswerner/cjsx.tmbundle#1]
I'm using Darcula theme, but when I use this tmbundle in a jetbrains product, the background colors are white etc (not at all like the lovely screenshot of the dark theme)

Has anyone else encountered this?

This has a white background, but should be dark:
![screen shot 2015-06-25 at 10 16 56 am](https://cloud.githubusercontent.com/assets/209970/8356439/54875f40-1b23-11e5-9ef8-3b92dbf355f8.png)

**Comment by rstudner** [comment]
Figured it out (duh):

So, on the screen for Textmate Bundles, below it is a little table that has "IDE color scheme =-> textmate color scheme" mapping.

So set Darcula on the left (IDE) & Darcula on the right (probably set to Mac Classic at the moment, which makes it white)

**Comment by se-panfilov** [comment]
@rstudner Same shit, thanks.

@ruswerner It would be better if you will add this info into readme =)

**Comment by ruswerner** [comment]
@se-panfilov sorry mate. I'm not supporting this anymore, but you can fork it if you like. It was actually quicker to convert our entire codebase to JavaScript/JSX than wait for JetBrains to build support into the tool; and we're better off anyway :)

**Comment by se-panfilov** [comment]
@ruswerner Okay, np. It's works anyway, and tbh I believe that we will move away from cjsx asap =)
