### ISSUE TITLE
Option to modify styles in Preferences > Editor > Colors & Fonts

### ISSUE THREAD

**Issue by globalchubby** [ruswerner/cjsx.tmbundle#2]
Thanks for writing this!

Is there a way to modify the style for `*.cjsx` files in `Colors & Fonts` in Webstorm? I don't see the option, like for the other file types `CoffeeScript`, `JavaScript`, `JSON`, etc.

It would be great if there were a way to do that.

**Comment by ruswerner** [comment]
I don't think so. AFAIK a tmbundle is just a thin wrapper on textmate bundles for backwards compatibility with that software product. As I've been advocating to others; it's probably better to just convert your code to JavaScript/JSX; less headaches and better all-round support.
