### ISSUE TITLE
Comment by "command"+"/" -> "#"

### ISSUE THREAD

**Issue by kosiakMD** [ruswerner/cjsx.tmbundle#3]
Thanks for this bundle,
But there is no config to comment lines by keypress "command"+"/" -> "#" :(
If is it possible please make in short time ;) the huge discomfort without that function =(

**Comment by george-cz** [comment]
@kosiakMD Hi, this is caused by the wrong path to config in package.json file. Open package.json in the plugin directory and edit `configuration` key to value `"configuration": "./cjsx.configuration.json"`. This fixed the issue for me.

**Comment by ruswerner** [comment]
I just re-bundled an existing textmate bundle so it would load in WebStorm; unfortunately I have no idea if what you are asking for is possible. This simply formats code into nice colours, it's not a proper plugin. You are probably better off just re-writing your code into proper JavaScript/JSX.
